Update git_submodule_update.yml

diff --git a/.github/workflows/git_submodule_update.yml b/.github/workflows/git_submodule_update.yml
--- a/.github/workflows/git_submodule_update.yml
+++ b/.github/workflows/git_submodule_update.yml
@@ -22,7 +22,7 @@ jobs:
           echo "Starting submodule sync --recursive..."
           git submodule sync --recursive || { echo "Submodule sync failed"; exit 1; }
           echo "Starting submodule update --init..."
-          git submodule update --init || { echo "Submodule initialization failed"; exit 1; }
+          git submodule update --init --recursive || { echo "Submodule initialization failed"; exit 1; }
           echo "Starting submodule update --remote..."
           git submodule update --remote || { echo "Submodule update failed"; exit 1; }
         shell: bash
