Update git_submodule_update.yml

diff --git a/.github/workflows/git_submodule_update.yml b/.github/workflows/git_submodule_update.yml
--- a/.github/workflows/git_submodule_update.yml
+++ b/.github/workflows/git_submodule_update.yml
@@ -21,10 +21,10 @@ jobs:
         run: |
           echo "Starting submodule sync --recursive..."
           git submodule sync --recursive || { echo "Submodule sync failed"; exit 1; }
-          echo "Starting submodule update --init..."
+          echo "Starting update --init --recursive ..."
           git submodule update --init --recursive || { echo "Submodule initialization failed"; exit 1; }
-          echo "Starting submodule update --remote..."
-          git submodule update --remote || { echo "Submodule update failed"; exit 1; }
+          echo "Starting submodule update --remote --merge ..."
+          git submodule update --remote --merge || { echo "Submodule update failed"; exit 1; }
         shell: bash
         
       - name: Download Moodle version file
